version: '2.1'

services:
  maccampersrepository:
    image: maccampersrepository
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    command: node --inspect index.js