<?php

return [
   'title_page' => "Conditions générales d'utilisation et de prestation de service",
   'title' => 'CGU',

   'intro' => "Les présentes conditions générales d’utilisation et des prestations de services (ci-après, les « CGU ») s’appliquent à l’utilisation de la plateforme de service mise en œuvre par Smartketing, Société par actions simplifiée au capital de 10,000 € dont le siège social est 84 avenue du Général Leclerc, 92100 Boulogne-Billancourt, immatriculée au R.C.S. de NANTERRE, sous le numéro 802 027 193 (ci-après, « EQUITEASY ») qui exploite le site internet http://equiteasy.com <u>et les url afférentes</u> (ci-après, le « Site » tel que défini en Article&nbsp;1).<br /><br />EQUITEASY se réserve le droit de modifier les CGU à tout moment. Les CGU applicables au moment de la création d’un projet (ci-après, le « Projet », tel que défini en Article&nbsp;1) seront applicables à l’ensemble des Utilisateurs intervenants dans le Projet (ci-après, « Utilisateurs », tel que défini en Article&nbsp;1).",

      'article_1_title' => "Article 1 – Définitions",
      'article_1' => "<p>« <strong>Site</strong> » : désigne la plateforme virtuelle et analogique dont les services fonctionnels et organisationnels mis en place sur internet par EQUITEASY sur son site internet http://equiteasy.com permettent aux Utilisateurs de bénéficier des Services rendus par EQUITEASY et d’être mis en relation avec les autres catégories d’Utilisateurs.<br/>
         « <strong>Opération(s)</strong> » : désigne la conclusion d’une opération de haut de bilan sur fonds propres ou quasi fonds propres et plus généralement toute opération touchant au capital ou à un transfert de part sociale ou d’obligation par un Entrepreneur que celle-ci soit mise en œuvre avec un autre Utilisateur ou avec un tiers.<br />
         « <strong>Entrepreneur</strong> » : désigne un Chef d’entreprise, dirigeant, porteur de Projet, etc. recherchant un Investisseur, une solution de financement ou ayant un Projet de cession de son entreprise.<br />
         « <strong>Conseiller</strong> » : désigne un Expert-comptable, avocat, Conseil en gestion de patrimoine, conseil M&A, etc. désireux d’accompagner ses clients dans leurs problématiques de financement.<br />
         « <strong>Investisseur</strong> » : désigne un Fonds d'investissement, family office, réseau de business angels et business angels.<br />
         « <strong>Repreneur</strong> » : désigne toute personne physique ou morale agissant à titre professionnel ayant un projet de reprise d’entreprise.<br />
         « <strong>Services</strong> » : désigne les services rendus par EQUITEASY dans le cadre du Site.<br />
         « <strong>Projet</strong> » : désigne le projet de recherche de solution de financement, d’investissement ou de cession ou de reprise de l’Entrepreneur.<br />
         « <strong>Utilisateur</strong> » : désigne toute personne physique ou morale agissant à titre professionnel ayant accepté les CGU et qui est un Entrepreneur, un Conseiller, un Investisseur ou un Repreneur. Tout Utilisateur s’engage à fournir des informations exactes quant à son identité, adresse et autres données nécessaires à l’accès de la Plateforme et de mettre à jour toute modification concernant ces informations.</p>",

         'article_2_title' => "Article 2 – Objet",
         'article_2' => "<p>Les présentes conditions générales d’utilisation du Site ont pour objet de définir les conditions selon lesquelles les Utilisateurs sont autorisés à utiliser le Site aux fins de bénéficier des Services leur permettant de réaliser des Opérations entre eux.</p>",

         'article_3_title' => "Article 3 – Obligation des utilisateurs",
         'article_3_1' => "Les Utilisateurs sont des personnes physiques ou morales agissant exclusivement à titre professionnel. Les Utilisateurs s’engagent à respecter les lois et règlements qui leurs sont applicables.",
         'article_3_2' => "En s’enregistrant auprès d’EQUITEASY, l’Utilisateur dispose d’un identifiant unique et d’un code d’accès nominatif strictement personnel qu’il s’engage à conserver confidentiels. L’Utilisateur enregistré, ou son représentant, est seul autorisé à utiliser le Site à l’aide de l’identifiant et du code d’accès nominatif. Dans l’hypothèse où il aurait connaissance de ce qu’une autre personne physique ou morale accède à celui-ci, l’Utilisateur informera EQUITEASY sans délai et confirmera par courrier cette information.",
         'article_3_3' => "L’Utilisateur s’engage à ne pas créer ou utiliser d’autres comptes que celui initialement créé, que ce soit sous sa propre identité ou celle de tiers. Toute dérogation à cette règle devra faire l’objet d’une demande explicite de la part de l’Utilisateur et d’une autorisation expresse et spécifique d’EQUITEASY. Le fait de créer ou d’utiliser de nouveaux comptes sous sa propre identification ou celle de tiers sans avoir demandé et obtenu l’autorisation d’EQUITEASY pourra entraîner la suspension immédiate des comptes de l’Utilisateur et de tous les services associés.",
         'article_3_4' => "<strong>L’Utilisateur s’engage à mettre à jour,</strong> dans les limites permises par EQUITEASY, <strong>ses informations et celles de sa société, le cas échéant.</strong>",
         'article_3_5' => "En cas de litige entre les Utilisateurs, les parties conviennent que la production par EQUITEASY des enregistrements sur les serveurs d’EQUITEASY de l’utilisation du Site et notamment des codes d’accès nominatifs feront foi entre les parties.",

         'article_4_title' => "Article 4 - Statut d'Equiteasy / Description des services et du processus de mise en œuvre des opérations",
         'article_4' => "<p>EQUITEASY met à disposition des Utilisateurs des Services et met en relation les Utilisateurs. Le Site est destiné aussi bien aux Entrepreneurs et à leurs Conseillers qu’aux Investisseurs et Repreneurs.</p><p>EQUITEASY fournit des ressources et des outils aux Entrepreneurs en quête de financement ou ayant un Projet de cession de leur entreprise en leur permettant de structurer et de gérer leur Projet sur le Site, de permettre à leurs Conseillers d’accéder à ces informations et d’être mis en relation avec des Investisseurs et/ou des Repreneurs. Le Site facilite ainsi les processus de levée de fonds et de transmission d’entreprise.</p><p>Le Site est une plateforme automatisant / digitalisant les levées de fonds et les transmissions d’entreprises, en s'appuyant notamment sur :</p><ul><li>une base de données ultra qualifiée de plusieurs centaines de fonds d’investissements et d’associations de business angel en Europe ;</li><li>un algorithme propriétaire,</li><li>un outil de structuration et de gestion intégré permettant aux parties prenantes de piloter facilement et intuitivement leurs Projets,</li></ul><p>Equiteasy propose un matching Projet-investisseur optimisé et participe ainsi à la réussite de cette étape cruciale pour les Entrepreneurs.<br />Le Site permet à l’Entrepreneur de piloter son Projet et discuter avec les investisseurs sur Equiteasy : Les investisseurs reçoivent la notification, vérifient que l’opportunité présente un intérêt, puis sont redirigés vers Equiteasy le cas échéant ;<br />Ils ont accès à quelques informations supplémentaires puis, si leur intérêt est confirmé, à une interface de signature d’engagement de confidentialité le cas échéant.<br />Une fois l’engagement de confidentialité signé (via notre prestataire de signature électronique Yousign), les investisseurs accèdent instantanément à l’ensemble des informations du projet préparées par l’Entrepreneur ou ses Conseillers :</p><ul><li>Formulaire rempli,</li><li>Documents téléchargés, etc.</li></ul><p>Les Utilisateurs mis en contact échangent durant tout le process sur le Site (messagerie interne, mise à disposition de documents).</p>",

         'article_5_title' => "Article 5 – Services aux entrepreneurs",
         'article_5' => "<p>Le Site permet aux Entrepreneurs de présenter leur Projet grâce à un formulaire spécifiquement étudié pour répondre aux attentes des Investisseurs, en particulier des fonds d’investissements. Le questionnaire, qui, une fois rempli, constitue l’équivalent d’un véritable mémorandum d’information, permet de présenter le Projet d’une manière permettant une mise en œuvre optimale des prises de contact avec les Investisseurs et Repreneurs.</p><p>L’Utilisateur doit remplir le questionnaire en renseignant a minima les champs obligatoires. La présentation de son Projet peut également être complétée par le téléchargement de documents (bilans, présentations commerciales, etc.) dans son espace sécurisé. Il doit ensuite signer électroniquement le contrat qui vise la rémunération détaillée à l’article 11 des présentes CGU.</p><p>L’algorithme d’EQUITEASY recherche alors les investisseurs les plus à-même d'être intéressés par le Projet de l’Entrepreneur, qui peut sélectionner ceux qu’il souhaite contacter et éventuellement en ajouter un ou plusieurs autres.</p><p>Les Investisseurs sélectionnés reçoivent par courriel un bref descriptif anonyme et confidentiel du Projet. Seuls les Investisseurs sélectionnés reçoivent le courriel afin d’assurer une parfaite confidentialité.</p><p>Les Investisseurs intéressés contactent l’Entrepreneur ou son Conseiller désigné directement ou via le Site afin d’accéder à l’ensemble des informations sur le Projet, après avoir signé électroniquement l’accord de confidentialité mis en ligne par l’Entrepreneur.</p><p>En parallèle, EQUITEASY rend à l’Entrepreneur des Services de gestion et de structuration de son Projet :</p><ul><li>Questionnaire de présentation du Projet ;</li><li>Signature électronique des documents par l’intermédiaire d’un prestataire reconnu ;</li><li>Gestion du Projet par l’intermédiaire d’un tableau de bord et d’un espace de messagerie intégré ;</li><li>Mise à disposition d’un espace sécurisé de téléchargement permettant de constituer une « data-room » ;</li><li>Possibilité de donner à tout moment l’accès à son Projet à un tiers (conseil, collaborateur, etc.) même si celui-ci n’est pas encore Utilisateur du Site.</li></ul>",

         'article_6_title' => "Article 6 – Services aux conseilleurs",
         'article_6' => "<p>Les Conseillers bénéficient d’un espace dédié qui leur permet de participer et gérer les Projets de leurs clients Entrepreneurs.</p>",

         'article_7_title' => "Article 7 – Services aux investisseurs",
         'article_7' => "<p>Pour les Investisseurs, EQUITEASY permet d’avoir accès en “push ” à un deal flow qualifié qui correspond à leur stratégie d’investissement.</p>",

         'article_8_title' => "Article 8 – Droit d'utilisation / Propriété",
         'article_8' => "<p>Dans le cadre de leur abonnement aux Services du Site, les Utilisateurs bénéficient du droit d’utilisation du Site et de ses composants et en particulier de l’algorithme de sélection des Investisseurs, non exclusif, révocable, et non transférable. <br />En aucun cas un quelconque droit sur le Site ou un quelconque élément du Site n’est transféré ou cédé à l’Utilisateur et restent la propriété exclusive d’EQUITEASY et/ou de ses donneurs de licence.<br /><br />L’Utilisateur reste seul titulaire des droits sur les contenus qu’il fournit à EQUITEASY.</p>",

         'article_9_title' => "Article 9 – Conseil",
         'article_9' => "<p>EQUITEASY n’a pas la qualité de conseil de l’Utilisateur à quelque titre que ce soit et EQUITEASY n’intervient pas dans le cadre des Opérations mises en œuvre par les Utilisateurs ne rendant que les Services aux Utilisateurs. EQUITEASY n’est ni courtier ni conseiller en investissements financiers.</p>
         <p><strong>EQUITEASY ne recommande aucun investissement, ne vérifie ou n’examine pas de manière exhaustive les documents ou les communications de l’Utilisateur, et ne donne pas de conseils commerciaux, de conseils financiers, de conseils d’investissement, de conseils fiscaux ou de conseils juridiques.</strong> EQUITEASY procède toutefois à une vérification formelle des informations communiquées par l’Entrepreneur afin de s’assurer de la complétude et de la bonne forme de son dossier. L’Entrepreneur est en conséquence pleinement et seul responsable des informations et données communiquées.</p>",

         'article_10_title' => "Article 10 – Rémunération d'Equiteasy / Paiement",
         'article_10' => "<p>Pour bénéficier des Services et en contrepartie du droit d’utilisation du Site, les Entrepreneurs et / ou leurs Conseillers seront redevable d’une rémunération qui se décompose en deux parties :</p>
         <ul>
         <li>Un abonnement mensuel d’un montant fixe dépendant de la durée de la souscription ;</li>
         <li>Une somme forfaitaire complémentaire qui sera due, en rémunération des Services :
            <ul>
            <li>si une Transaction fait l’objet d’un accord engageant dans un délai maximal de 18 mois à compter de l’acceptation des présentes CGU ;</li>
            <li>cette somme forfaitaire sera due quand bien même l’Opération serait mise en œuvre en ne recourant que partiellement à l’intermédiaire du Site et/ou si elle était finalement conclu avec un investisseur qui n’est pas un Investisseur ;</li>
            <li>cette somme forfaitaire sera payable dès que l’Opération sera effectivement mise en œuvre, à savoir :
               <ul>
               <li>Le versement du premier euro dans le cadre d’un financement ;</li>
               <li>Le transfert de la première action ou obligation dans le cadre d’une cession d’action ;</li>
               </ul>
               </li>
               </ul>
               </li>
               </ul>
               <p>Afin de lever tout doute, il est précisé que la rémunération forfaitaire d’Equiteasy restera due quand bien même l’Utilisateur ne serait plus lié par un abonnement au moment de la mise en œuvre effective de l’Opération.</p>
               <p>Un modèle de contrat pourra vous être envoyé sur simple demande à <a href=\"mailto:contact@equiteasy.com\">contact@equiteasy.com</a>.</p>
               <p>Les Investisseurs bénéficieront d’une inscription et de droit d’utilisation du Site à titre gratuit. Ils pourront toutefois se voir facturer des Services spécifiques complémentaires tels que :</p>
               <ul>
               <li>La recherche d’un repreneur ;</li>
               <li>La possibilité de créer de nouvelles stratégies d’investissement, notamment pour identifier des opportunités d’acquisition pour les participations de l’Investisseur.</li>
               </ul>
               <p>Les différents prix seront présentés et acceptés par l’Utilisateur au moment de la souscription aux Services. Ils seront formalisés dans un contrat dont les présentes CGU feront partie intégrale. Ce contrat sera, le cas échéant, signé par les Utilisateurs lors de la phase de constitution de leur Projet sur EQUITEASY. </p>
               <p>Les factures d’EQUITEASY sont payables comptant. Conformément à la loi, il est précisé qu’à défaut de paiement dans les délais, sont applicables de plein droit et sans mises en demeure, des pénalités de retard d’un montant égal à trois fois le taux d’intérêt légal ainsi que des frais de recouvrement forfaitaire de 40 € et si ces frais sont supérieurs au montant de cette indemnité forfaitaire, une indemnisation complémentaire, sur justification.</p>",

               'article_11_title' => "Article 11 – Responsabilités",
               'article_11' => "<p>EQUITEASY n'examine pas et ne vérifie pas l’ensemble du contenu mis en ligne par les Utilisateurs, et ne garantit ni ne peut garantir que tout contenu mis en ligne par les Utilisateurs est authentique, précis ou complet.</p><p>Il appartient aux Utilisateurs de vérifier la pertinence et l’authenticité des informations, et contenus mis à leur disposition sur le Site. La responsabilité d’EQUITEASY ne pourra en aucun cas être engagée en raison d’une faute ou d’un manquement de l’un des Utilisateurs qui est seul responsable de ses actes vis-à-vis des autres Utilisateurs. </p><p>Les Utilisateurs sont informés qu’EQUITEASY ne peut garantir un accès 24h/24h au Site et que celui-ci peut être indisponible pendant des périodes normales de maintenance. EQUITEASY garantit toutefois, hors période de maintenance, un taux de service de 99%.</p><p>La responsabilité d’EQUITEASY est limitée aux dommages directs à l’exclusion de tout dommage indirect, consécutif, incident, punitif, etc.</p><p>En aucun cas, la responsabilité d’EQUITEASY ne pourra être engagée au-delà du montant effectivement payé par l’Utilisateur dans le cadre du Projet pour lequel il entend mettre en cause la responsabilité d’EQUITEASY.</p><p>L’Utilisateur sera responsable vis-à-vis d’EQUITEASY et/ou des autres Utilisateurs de toute utilisation frauduleuse du Site, de la mise en ligne de tout contenu illicite, illégal, frauduleux ou délictueux. En particulier, l’Utilisateur sera responsable en cas de propagation de tout virus, logiciel espion ou programmes qui y sont assimilés et sera tenu d’indemniser EQUITEASY et les autres Utilisateurs de l’ensemble des dommages qu’ils pourraient subir de ce fait.</p>",

               'article_12_title' => "Article 12 – Résiliation",
               'article_12_1' => "Les relations entre EQUITEASY et l’Utilisateur sont à durée indéterminée sauf si l’Utilisateur a souscrit un abonnement avec engagement. Sauf souscription d’un abonnement avec engagement, il est résiliable à tout moment par EQUITEASY ou par l’Utilisateur sans motif particulier par notification par email ou par lettre recommandée avec demande d’avis de réception. L’abonnement prendra fin à la fin de la période de facturation en cours.",
               'article_12_2' => "En cas de souscription à un engagement à durée déterminée, cet engagement sera renouvelé par tacite reconduction pour des périodes successives d’une durée égale à la durée initiale d’engagement, sauf dénonciation par l’une des parties avec un préavis d’un (1) mois avant l’arrivée du terme initial ou d’une période de renouvellement.",
               'article_12_3' => "Si l’Utilisateur souscrit un abonnement sans engagement de durée, l’Utilisateur est engagé pour une période mensuelle. L’abonnement sera renouvelé par tacite reconduction par périodes d’un (1) mois, sauf dénonciation par l’Utilisateur ou Equiteasy avant l’arrivée du terme initial ou d’une période de renouvellement.",
               'article_12_4' => "En cas de faute commise par un Utilisateur, telle que la fraude aux moyens de paiement, tentatives d’escroquerie ou tout autre infraction pénale, mise en ligne de tout contenu illicite, illégal, frauduleux ou délictueux, propagation de virus, logiciel espion ou programmes qui y sont assimilés, ou non respect des présentes CGU, EQUITEASY se réserve la faculté de suspendre ou résilier l’accès de l’Utilisateur au Site, sans préjudice de l’indemnisation de l’entier dommage éventuellement subi par EQUITEASY et les autres Utilisateurs. En cas de suspension, l’Utilisateur restera tenu du paiement de la somme forfaitaire éventuellement due en cas de réalisation de l’Opération. En cas de résiliation, l’Utilisateur restera tenu de l’entier paiement de la rémunération d’EQUITEASY.",

               'article_13_title' => "Article 13 – Confidentialité",
               'article_13' => "<p>EQUITEASY apporte une importance très forte à la confidentialité des données, informations et contenus qui sont mis en ligne par les Utilisateurs.</p><p>A cette fin, EQUITEASY a mis en place un système d’hébergement des données, informations et contenus de chaque Utilisateur sur des serveurs différents afin d’éviter qu’un tiers puisse avoir accès à un dossier identifié complet.</p><p>EQUITEASY s’engage à ce titre à ne communiquer des informations à un autre Utilisateur que sous réserve de l’accord préalable de l’Utilisateur.</p><p>EQUITEASY s’engage à ce titre à ne pas communiquer les informations d’un Utilisateur à une personne qui ne serait pas Utilisateur.</p>",

               'article_14_title' => "Article 14 – Dispositions générales",
               'article_14_1' => "EQUITEASY a la faculté de modifier les présentes conditions générales en fonction de l’évolution de son offre et du marché. Toute modification prendra effet immédiatement pour les offres en ligne dès leur notification aux Utilisateurs par tout moyen choisi par EQUITEASY. Elles ne s’appliqueront par pour les Opérations en cours au moment de leur entrée en vigueur. Occasionnellement EQUITEASY pourra changer de code, numéros de téléphone, interrompre le service pour des raisons opérationnelles, de maintenance ou en cas d’urgence de de force majeure.",
               'article_14_2' => "L’Utilisateur se connectera à la Plateforme au moyen de ses propres équipements terminaux de télécommunications. EQUITEASY ne met à disposition de l’Utilisateur aucun moyen matériel, installation téléphonique, équipement terminal ou autres, ni logiciel ni abonnement.",
               'article_14_3' => "<p>En cas de force majeure, les obligations de la partie empêchée seront suspendues, notamment en cas :</p><ul><li>d’acte ou omission du gouvernement ou d’autorité supérieures compétentes,</li><li>de blocage ou défaillance des réseaux de télécommunications,</li><li>d’insurrections, guerre civile, guerre, opérations militaires, état d’urgence national ou local,</li><li>de feu, de foudre, explosion, d’inondation, de tempête,</li><li>de grève, de fait d’un tiers.</li></ul>",
               'article_14_4' => "L’invalidité d’une ou plusieurs clauses des CGU n’entraînera pas la nullité des autres clauses.",

               'article_15_title' => "Article 15 – Protection des données personnelles",
               'article_15_1' => "<p>Le site EQUITEASY est enregistré à la CNIL sous le numéro 2071992 v 0.<br />Il est rappelé que les informations personnelles recueillies à l’occasion des Opérations enregistrées font l’objet d’un traitement automatisé. Les données enregistrées sont utilisées pour répondre aux différents services en ligne proposés par la Plateforme. Par l’approbation des présentes CGU, l’Utilisateur donne son accord à ladite utilisation des données le concernant.Conformément à la loi n° 78-17 du 6 janvier 1978 relative à l'informatique et aux libertés, tout Utilisateur dispose d'un droit d'accès et de rectification ou de suppression des informations nominatives le concernant. Ce droit peut être exercé, à tout moment, par les moyens suivants : par formulaire mail mis à votre disposition dans la page de «contact » ou par courrier postal adressé à EQUITEASY (84 avenue du GénéralLeclerc,92100Boulogne-Billancourt) ou par courriel (<a href=\"mailto:contact@equiteasy.com\">contact@equiteasy.com</a>).</p>",
               'article_15_2' => "<p>L’Utilisateur peut accéder à tout moment aux informations le concernant et procéder aux modifications qu’il estime nécessaires à partir de son espace personnel sécurisé accessible directement sur le site. Il ne pourra toutefois pas modifier les informations communiquées dans le cadre de la présentation de son Projet.<br /><br />Les photographies et les textes reproduits sur le Site sont entièrement sous la responsabilité des Utilisateurs.</p>",

               'article_16_title' => "Article 16 – Loi applicable / Tribunal compétent",
               'article_16' => "<p>Les CGU sont régies par les dispositions de la loi française. Tout différend né à l'occasion de leur interprétation et/ou de leur exécution qui ne pourrait être résolu de manière amiable sera de la compétence exclusive du Tribunal de commerce de Paris. </p>",
            ];
